# Generated by Django 3.0.8 on 2020-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200826_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_genre',
            field=models.CharField(choices=[('Anything', 'NA'), ('Young Adult', 'YA'), ('Romance', 'RO'), ('Fantasy', 'FA'), ('Sci-Fi', 'SF'), ('Non-Fiction', 'NF'), ('Graphic Novels & Comics', 'GN'), ('Mystery', 'MY'), ('Historical Fiction', 'HF'), ('Horror', 'HO'), ('Thriller', 'TH'), ('Poetry', 'PO')], max_length=100),
        ),
    ]
