# Generated by Django 3.0.8 on 2020-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200831_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Anything', 'Anything'), ('Young Adult', 'Young Adult'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Non-Fiction', 'Non-Fiction'), ('Graphic Novels & Comics', 'Graphic Novels & Comics'), ('Mystery', 'Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Poetry', 'Poetry')], max_length=100),
        ),
    ]
