# Generated by Django 3.0.8 on 2020-08-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200822_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.Project'),
        ),
    ]
