# Generated by Django 3.0.8 on 2020-08-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200824_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('YA', 'Young Adult'), ('RO', 'Romance'), ('FA', 'Fantasy'), ('SF', 'Sci-Fi'), ('NF', 'Non-Fiction'), ('GN', 'Graphic Novels & Comics'), ('MY', 'Mystery'), ('HF', 'Historical Fiction'), ('HO', 'Horror'), ('TH', 'Thriller'), ('PO', 'Poetry')], default='Romance', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.Project'),
        ),
    ]
