# Generated by Django 3.0.8 on 2020-08-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200826_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Anything', 'NA'), ('Young Adult', 'YA'), ('Romance', 'RO'), ('Fantasy', 'FA'), ('Sci-Fi', 'SF'), ('Non-Fiction', 'NF'), ('Graphic Novels & Comics', 'GN'), ('Mystery', 'MY'), ('Historical Fiction', 'HF'), ('Horror', 'HO'), ('Thriller', 'TH'), ('Poetry', 'PO')], max_length=100),
        ),
    ]
