# Generated by Django 3.0.8 on 2020-08-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200826_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_closed',
            field=models.DateTimeField(),
        ),
    ]
